### ISSUE TITLE
Uncontrolled data used in path expression vulnerability fix

### ISSUE THREAD

**Issue by rphacker1618** [mgrybyk/allure-report-branch-js-action#18]
Hi @mgrybyk  , can you please help in updating this action with below commit code from allure-report-branch-action in order to to fix Uncontrolled data used in path expression vulnerability
https://github.com/mgrybyk-org/allure-report-branch-action/pull/21/commits/17a408be667ae2c6272846e0423b65c2b0a0afb5
https://github.com/mgrybyk-org/allure-report-branch-action/pull/21

**Comment by mgrybyk** [comment]
Hello @rphacker1618,

I'm glad to help. However, I didn't get what problem you want to solve.
Can you please provide more details.

Is it a security vulnerability or a functional defect?

**Comment by rphacker1618** [comment]
Hi @mgrybyk,

This is security vulnerability detected by CodeQL tool from GitHub , here are the screenshot and code snippet suggested by CodeQL . Kindly Help me in resolving this vulnerability.

Also one request, can you please provide steps to set up the source code onto our local machine.

Thanks,
Ravi

<img width="566" alt="CodeQL_Vulnerability" src="https://github.com/user-attachments/assets/dac16b1c-5caa-44a8-8bde-a65e0aac583d">
<img width="340" alt="Missing_regular_expression_anchor_recommendation" src="https://github.com/user-attachments/assets/d6e14bf9-106f-4b6a-96d2-9eeabdc7973d">
<img width="347" alt="UnControlled_data_used_in_path_expression_recommendation_1" src="https://github.com/user-attachments/assets/5ce8892e-ea0d-4432-819b-7fbde030a252">
<img width="356" alt="UnControlled_data_used_in_path_expression_recommendation_2" src="https://github.com/user-attachments/assets/daadcfbc-3775-43b3-a004-64090041a366">
<img width="347" alt="UnControlled_data_used_in_path_expression_recommendation_3" src="https://github.com/user-attachments/assets/8628f0ad-e653-4670-8d8e-0f2c2efbdc47">

**Comment by mgrybyk** [comment]
@rphacker1618 you may safely ignore these warnings. All of them are false positive.

Feel free to raise a PR to overcome this if you like.
I'm closing the issue but we can keep chatting.

> can you please provide steps to set up the source code onto our local machine

I don't know what you mean.
