### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by vladburian1** [mgrybyk/allure-report-branch-js-action#19]
here is my yaml
     - name: Build test report
        uses: mgrybyk-org/allure-report-branch-js-action@v1.4.4
        id: allure
        if: always()
        with:
          list_dirs: true
          report_id: 'self-test'
          gh_pages: 'gh-pages-dir'
          report_dir: 'target/allure-results'

Error: no such file or directory: gh-pages-dir/allure-action/master/self-test/10172744184_1722393460519/history

**Comment by mgrybyk** [comment]
@vladburian1 you may temporary delete file in your gh-pages branch `allure-action/master/self-test/lastRun.json`.

This issue happened because lastRun.json contains reference to a run that doesn't. I'll fix it later.
